Comics CLI with Worker Pool
AfoninaOlga/Golang-Course pull request #6
Opened 2024-04-12 21:51 UTC by AfoninaOlga

**DONE**
- [x] Добавлен worker pool
- [x] Оставлена промежуточная запись в файл
- [x] Нахождение пропущенных в БД индексов
- [x] Отправка запросов только для отсутствующих в БД комиксов

**TODO**
- [ ] Обработка cntrl-c
- [ ] Число воркеров

2024-04-14 16:19 UTC, vbelogrudov requested changes
Привет!

очень неплохо, есть предложения по реструктуризации/упрощению

2024-04-14 16:19 UTC, vbelogrudov commented on pkg/database/json.go
> +	jb.mtx = &sync.Mutex{}
в данном случае указатель необязателен

2024-04-14 16:19 UTC, vbelogrudov commented on pkg/database/json.go
>  func (jb *JsonDatabase) Flush() (err error) {
можно сделать приватным flush, а FlushParallel переименовать  во Flush.

2024-04-14 16:19 UTC, vbelogrudov commented on pkg/database/json.go
> +	mtx    *sync.Mutex
хорошая идея спрятать мьютекс от клиента! В Го мьютекс считается низкоуровневой конструкцией (в сравнении с goroutine/channel), поэтому его как раз лучше прятать внутри структур и их методов

2024-04-14 16:19 UTC, vbelogrudov commented on pkg/database/json.go
> +	err := jb.Flush()
можно сразу return jb.Flush(), дело вкуса

2024-04-14 16:19 UTC, vbelogrudov commented on pkg/database/json.go
> +func (jb *JsonDatabase) AddComicParallel(id int, c Comic) {
тоже можно оставить публичным конкурентный метод и спрятать однопоточный.

2024-04-14 16:19 UTC, vbelogrudov commented on cmd/xkcd/main.go
> +func getParallel(xkcdClient *xkcd.Client, db *database.JsonDatabase, jobs <-chan int, done chan<- bool) {
вместо done chan лучше использовать sync.WaitGroup

2024-04-14 16:19 UTC, vbelogrudov commented on cmd/xkcd/main.go
> +		if i%50 == 0 {
как-то часто мы проверяем i%50 == 0

2024-04-14 16:19 UTC, vbelogrudov commented on cmd/xkcd/main.go
> +		if i%50 == 0 {
про Flush, а нужно ли нам здесь делать его?  defer db.Flush() в самом начале хватило бы. А промежуточные делать в db.Add ...

2024-04-14 16:19 UTC, vbelogrudov commented on cmd/xkcd/main.go
> +	//waiting for workers to finish
wg.Wait() // sync.WaitGroup

2024-04-15 09:56 UTC, AfoninaOlga commented on pkg/database/json.go
> +	jb.mtx = &sync.Mutex{}
Оставила указатель, так как линтер ругается на `return copies lock value` в [функции New](https://github.com/AfoninaOlga/Golang-Course/blob/f9d9456e3dfebc17a5de34e54ad969ac59f83d1d/pkg/database/json.go#L24C2-L24C8)

2024-04-15 21:29 UTC, AfoninaOlga commented
Число горутин в конфиге — 64, так как:
- с 4 до 60 горутин время работы заметно уменьшается
- с 60 до 500 горутин время работы примерно одинаковое (~11 секунд);
- от 500 до 2000 время около 10 секунд, но больше использование ресурсов, одновременных запросов к xkcd и лишних запросов (получающих код 404 для распознавания конца списка комиксов)

2024-04-16 07:10 UTC, vbelogrudov approved these changes
все уже хорошо работает, но есть пути улучшить еще, сейчас или уже в следующем задании :)

2024-04-16 07:10 UTC, vbelogrudov commented on cmd/xkcd/main.go
> +		go worker(client, comicDB, jobs, &wg, &cancelFunc)
воркеру необязательна cancelFunc, он просто может выйти. А мы запустим
```
go func() {
    wg.Wait()
    close(jobs)
    cancelFunc()
}
```

2024-04-16 07:10 UTC, vbelogrudov commented on cmd/xkcd/main.go
> +	for {
"feeder" можно сделать проще,
 ```
for {
     select
      case <-ctx.Done() // break loop, someone called cancelFunc()
      case jobs <- curId:
           if exists in db -> continue
           curId++
```

2024-04-16 07:10 UTC, vbelogrudov commented on cmd/xkcd/main.go
> +	c := make(chan os.Signal, 1)
лучше signal.NotifyContext(ctx, os.Interrupt)

2024-04-18 14:46 UTC, merged